### ISSUE TITLE
Add detail page functionality for credentials (New page) design link

### ISSUE THREAD

**Issue by puria** [ForkbombEu/wallet#117]
![Image](https://github.com/ForkbombEu/wallet/assets/26438256/7da1c1a1-c82d-478b-b4ac-d7acd8da8c91)

**Comment by micolsalomone** [comment]
https://www.figma.com/file/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?type=design&node-id=2377%3A4422&mode=design&t=sUZY4XvBEXDHsVSJ-1

**Comment by micolsalomone** [comment]
@phoebus-84 I need updates on this issue, talk soon!
