### ISSUE TITLE
Profile page design update + Profile submenu (New page) 

### ISSUE THREAD

**Issue by micolsalomone** [ForkbombEu/wallet#164]
New profile page: 
https://www.figma.com/file/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?type=design&node-id=3228%3A4704&mode=design&t=dWyzyOXQ9Y14xBmW-1

<img width="824" alt="Screenshot 2024-02-28 alle 13 27 15" src="https://github.com/ForkbombEu/wallet/assets/26438256/01493905-d3c5-422d-bc10-43eff3446a9a">

Profile Menu pages:
- [ ] Language settings
- [x] Notification settings
- [x] Logout
- [ ] Security and authentication (design is missing)

**Comment by puria** [comment]
superseeded by #348
