### ISSUE TITLE
POST in in the Oauth flow should be done in Slangroom

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/wallet#187]
This POST

https://github.com/ForkbombEu/wallet/blob/main/src/lib/openId4vci/index.ts#L54-L57

Should be done in Slangroom. The .ts code should ONLY store/read states between parts of the flow

**Comment by puria** [comment]
Agree! You can add it at the end of https://github.com/ForkbombEu/wallet/blob/main/src/lib/openId4vci/zencode/holder_to_par_on_authz_server.zen
