### ISSUE TITLE
Wallet-initiated credential request according to OpenID4VCI

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/wallet#194]
We currently initiate credential request by having the wallet scanning a qr containing this: 

```
{
	"scope": "Auth1",
	"relying_party": "https://relying-party1.zenswarm.forkbomb.eu/relying_party",
	"resource": "https://issuer1.zenswarm.forkbomb.eu/credential_issuer",
	"authorization_server": "https://authz-server1.zenswarm.forkbomb.eu/authz_server",
	"id": "xw012cz9fcjg9hf"
}
```

in order to be compatible with the [OpenID4VCI standard](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-authorization-code-flow) (in the sub-section 1b) we need a qr code like: 

```
{
	"credential_configuration_ids": ["Auth1"]
	"credential_issuer": "https://issuer1.zenswarm.forkbomb.eu/credential_issuer"
}

```

Meaning that: 
- the "relying party" is not needed at all. 
- "resource" -> "credential_issuer"
- "scope": "string"  ->  "credential_configuration_ids": ["name of the credential(s) to be issued"], for now we can assume that only one credentials will be present in the array.
 

- The information contained in "id" and should be read from the credential issuers's .well-known [file](https://issuer1.zenswarm.forkbomb.eu/credential_issuer/.well-known/openid-credential-issuer), specifically by finding the credential "Auth1" in the array "credential_configurations_supported" 
- The information contained in "authorization_server" should be read from the credential issuers's .well-known [file](https://issuer1.zenswarm.forkbomb.eu/credential_issuer/.well-known/openid-credential-issuer) from the key "authorization_servers": ["url1", "url2"]. The Wallet GUI should (!) allow the user to choose which authz_server they want to use, but at this point it's enough that the wallet **picks the first authz_server from the array**.

**Comment by puria** [comment]
This should also be handled in signroom to showthe correct QR @bbtgnn (as just said, the info in the QR should change... like this) <3
