### ISSUE TITLE
Add lottie animation file in "Generating Keypair"

### ISSUE THREAD

**Issue by micolsalomone** [ForkbombEu/wallet#199]
add lottie animation to this screen: 
![Image](https://github.com/ForkbombEu/wallet/assets/26438256/23137f96-b565-4380-bac6-8559e20598b7)

lottie link: https://app.lottiefiles.com/share/6c2f4bae-9f3b-443a-b694-d8bcca6172d8

figma link: https://www.figma.com/file/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?type=design&node-id=3398%3A20406&mode=design&t=uoK5mNgNMs48VI9c-1

**Comment by phoebus-84** [comment]
Can you point also to an animation for light mode?

**Comment by micolsalomone** [comment]
Here is the light theme version: https://app.lottiefiles.com/animation/dcc73084-8ef9-4431-bc7a-37827111c61e

@phoebus-84
