### ISSUE TITLE
When drawing an image (avatar) from an URL, the background should be white

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/wallet#225]
Here: 

https://gyazo.com/3789b93a8dc3afe73ebed30303048350

we're loading this picture: http://blog.citizenkey.eu/public/Graphics/.ZafeLog__logo_s.png

Which has a transparent background: https://gyazo.com/67540b1ea59b9834880edaa260b83756

therefore when loading a picture (which may or not have a transparent background) the background should be white maybe with some transparency (256, 256, 256, .8).

To reproduce, try to obtain this credential:

{
 "credential_configuration_ids": [
  "above16"
 ],
 "credential_issuer": "https://issuer1.zenswarm.forkbomb.eu/credential_issuer"
}

**Comment by phoebus-84** [comment]
Addressed in #425
