### ISSUE TITLE
Improve Verification flow for Holder App

### ISSUE THREAD

**Issue by micolsalomone** [ForkbombEu/wallet#256]
- Users need more info about WHO is requesting the verification
- Users need more control over what data they are sharing with the verifier
- Users need review and confirmation of their choices

**Comment by micolsalomone** [comment]
design to be confirmed

**Comment by micolsalomone** [comment]
<img width="879" alt="image" src="https://github.com/ForkbombEu/wallet/assets/26438256/709178e9-c810-4a3d-b8c8-ca3c9ba47eef">
@puria

**Comment by puria** [comment]
I do feel that we have the info arch in place.
Some minor comments:
 * I guess we don't have the auth server, it's more important to show in place the relying party (who is going to check and validate your information)
 * Minor copy details: you can't 'choose' between the different credentials (by now, dunno in the future)

Overall great job 😘

A suggestion (not really of this issue, but just passed away in my mind) in many of our transaction we have the business logic written in zencode (plain English). For very nerd people and for democratic data sovereign transparency:
would be very cool to have something like an icon that allows always to check the details of what/which smart contract is going to be executed.

 Not always shown, like when you accept a privacy policy, but if you want to, you can follow a link and check what is happening under the hood.


Double check that there are not any time data we can show (expiry? How long the verifier can see our data? How long the relying party can see your data, etcccc)
In case we have them it's fundamental to show them to the citizens.

**Comment by micolsalomone** [comment]
Totally agree on all points, talk soon.
