### ISSUE TITLE
Use KeyStore on Android

### ISSUE THREAD

**Issue by albertolerda** [ForkbombEu/wallet#31]
For Android devices TEE is a mandatory requirement for OEMs to obtain Google Mobile Services (GMS) licensing for devices that have Google apps pre-installed (https://android.stackexchange.com/a/233747)

We can store the zenroom keyring encrypted (using symmetric encryption) on the usual storage and save the private key in the `KeyStore` (https://developer.android.com/training/articles/keystore)

Using the `KeyStore` the key material is never exposed outside the TEE (trusted execution environment) or SE (secure element) ( https://developer.android.com/training/articles/keystore#ExtractionPrevention )

Algorithms supported by TEE:
- RSA 2048
- AES 128 and 256
- ECDSA, ECDH P-256
- HMAC-SHA256 (supports key sizes between 8 bytes and 64 bytes, inclusive)
- Triple DES
- Extended Length APDUs
- Key Attestation

**Comment by puria** [comment]
This coulb be don in kotlin or java up to you @matteo-cristino
