### ISSUE TITLE
When try to re-register a user the feedback message should be fixed (now logs slangroom)

### ISSUE THREAD

**Issue by puria** [ForkbombEu/wallet#357]

**Comment by phoebus-84** [comment]
shall we check the email it is not yet registered before proceed and ask for password?

**Comment by phoebus-84** [comment]
In fact, I would suggest to check if email is already registered in the route before and show a meaningful error there, before proceed and ask for passwords.
Something like this:
![output](https://github.com/ForkbombEu/wallet/assets/83974413/3de1652b-bdb5-4490-8c40-174d890b2d52)
