### ISSUE TITLE
Implement push notification service

### ISSUE THREAD

**Issue by puria** [ForkbombEu/wallet#40]
Let's start by Android:

- I don't mind if we start with firebase
- Alternatives are also okay
- Setup the dev environment <--

**Comment by phoebus-84** [comment]
### Android:

1. **On-Premise Solutions:** I've evaluated on-premise options like ntfy and gotify, but given the user experience concerns and potential issues with device battery optimization, we've opted against them. While they are cool software, ensuring a seamless notification experience for the end user is a top priority.

2. **Firebase and Google Services:** We've decided to go with Firebase and leverage Google services. This choice provides a relatively easy setup, especially with the capacitor plugin. This not only streamlines the implementation process but also aligns well with industry standards for robust push notification services.

3. **App Instance Token:** To send messages to individual users, we'll utilize the app instance token provided by Firebase after the user grants permission for notifications. This ensures a targeted and efficient approach to delivering notifications to specific users.

I'll proceed with the implementation based on these decisions.
