### ISSUE TITLE
Not perfectly aligned load symbol and titles and card size

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/wallet#434]
Trying the app from last last release on app tester (should be from #433)
* loading symbol is not centered in some page
  ![image](https://github.com/user-attachments/assets/3ab66c08-f6ce-460f-85e2-3d003e9d8bb8)
* profile title is not centered (due to the gear setting symbol maybe)
  ![image](https://github.com/user-attachments/assets/8ae7fe13-952e-443d-808d-4c4a82a76639)
* language title is not centered (due to the left arrow symbol maybe)
  ![image](https://github.com/user-attachments/assets/2f1c41f1-aed6-41b0-be4b-781fb33b3ead)
* credential card have different sizes based on the test in them
  ![image](https://github.com/user-attachments/assets/29c08529-d2ca-403f-8407-f2dd272da728)

(Sorry for the huge image did not know how to rescale them)

**Comment by puria** [comment]
Yeah I guess because needs this: https://github.com/ForkbombEu/didroom-components/pull/129

That I just merged!
Could retry in 20min... the god of the cdn networks can willing to need some sacrifice!

**Comment by matteo-cristino** [comment]
The problem with the credential card is fixed, the other are still there (titles and loading not centered)

**Comment by phoebus-84** [comment]
Thanks for your reports! I think now should be solved also the problem with loading. For the header we need this pr: https://github.com/ForkbombEu/didroom-components/pull/131

**Comment by puria** [comment]
Just merged https://github.com/ForkbombEu/didroom-components/pull/131
