### ISSUE TITLE
Change app name to DIDroom Wallet

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/wallet#441]
You also do this in the manifest (https://github.com/ForkbombEu/wallet/blob/main/android/app/src/main/AndroidManifest.xml)

https://stackoverflow.com/questions/5443304/how-to-change-an-android-apps-name

**Comment by puria** [comment]
This should be handled by capccitor, since it's autogenerated, and please double check that the iOS works also. Because that is the one that have more problems. Do not change by any mean the manifest by hand ;p

**Comment by puria** [comment]
I also suggest to have Wallet with all lower case... and also take into consideration the hyphen of the devices... that will probably cut it to `DIDr..llet` I do not recall how many words are allowed before hyphening
