### ISSUE TITLE
Holder should choose which credential to present, if multiple credentials match the presentation request 

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/wallet#445]
@micolsalomone and @phoebus-84 already working on it

**Comment by micolsalomone** [comment]
<img width="643" alt="image" src="https://github.com/user-attachments/assets/e7a1eef7-458c-4cba-af71-205433fb81ba">
1st proposal for credential selection - and improvement for verification detail (1st screen)

**Comment by micolsalomone** [comment]
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/3d5f6892-9150-4d59-b8ce-c4bd7b9a40c6">
2nd proposal for verification and claims disclosure flow
Figma link: [https://www.figma.com/design/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?node-id=4532-53488&t=a6Qmb0ojYZ0U0HAt-1](https://www.figma.com/design/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?node-id=4532-53488&t=a6Qmb0ojYZ0U0HAt-1)

**Comment by micolsalomone** [comment]
3rd proposal 
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/b8286959-2b56-4e89-88cd-4cfb56ca3d2f">
[https://www.figma.com/design/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?node-id=4532-53488&t=RXo0Ny2wnIP1kA3n-1](https://www.figma.com/design/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?node-id=4532-53488&t=RXo0Ny2wnIP1kA3n-1)

**Comment by phoebus-84** [comment]
addressed here: #479
