### ISSUE TITLE
UX improvements on credential presentation flow

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/wallet#471]
A misc list of issues, need actions from @micolsalomone and @phoebus-84 

- [ ] In the first step, when the list of cards is presented, the claims (keys and values) must be visible for each card
- [ ] Button "Verify" must be sticky, list of credentials must scroll under the button
- [ ] URL is not shortened and goes out of the box
- [ ] Microcopy, change "Choose credential" to "Present credential"

Then, after presentation started (https://gyazo.com/4f139eb94a07f598414f1b13bff00f23)
- [ ] Change "Verified" with "In progress"
- [ ] Make the color of the checkbox AND of the session ID, transparent at 50% (or @micolsalomone please advice)

**Comment by micolsalomone** [comment]
Updated on Figma: https://www.figma.com/design/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?node-id=4532-53488&t=RGKmvsOBMuyIGlSz-1

@phoebus-84
